export const userFilterActionTypes = {
  UPDATE_SEARCH_QUERY: 'UPDATE_SEARCH_QUERY',
  UPDATE_FILTER_LIST: 'UPDATE_FILTER_LIST',
  UPDATE_SELECTION_LIST: 'UPDATE_SELECTION_LIST',
  UPDATE_CURRENT_SELECTION: 'UPDATE_CURRENT_SELECTION',
  RESET_FILTER: 'RESET_FILTER',
};
